### ISSUE TITLE
avast doesn't like 0.16

### ISSUE THREAD

**Issue by CodingGlitch** [ForLoveOfCats/SkyOfSteel#73] opened 2019-12-04 19:23 UTC
It considers it a "rare file" and will NOT let you open it.
Weird.

**Comment by ForLoveOfCats** [comment] 2019-12-04 21:31
This was an issue before but within an hour of being reported as a false positive neither the initial reporter nor I was able to reproduce. It's almost certainly back because of the update classifying it as a new file. I don't know what all can be done in this situation. I'll look into contacting Avast somehow.

**Comment by Zireael07** [comment] 2019-12-05 07:29
"Rare files" being blocked is an ANTI-feature of many modern AV programs, not just Avast. And it hasn't been abandoned in spite of many people complaining.

**Comment by ForLoveOfCats** [comment] 2019-12-11 17:12
Shit :sweat_smile:

**Comment by ForLoveOfCats** [comment] 2019-12-11 17:22
So after fighting with it a bit I've just submitted a false positive report to Avast. I'll close this when I get an email back or if nothing happens for a few weeks

**Comment by ForLoveOfCats** [comment] 2019-12-13 03:42
I've received email confirmation from Avast that their product does not (now) detect 0.1.6 as a threat of any kind. This will probably have to be repeated with the next release (which is due asap due to issues with 0.1.6 on Windows).

**Closed by ForLoveOfCats** 2019-12-13 03:42 UTC
